name: bangu_lite
description: "Lite to Surf Bangumi"
publish_to: 'none'
version: 0.10.3
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^5.2.1
  app_links: ^6.4.0

  cached_network_image: ^3.4.1
  dio: ^5.6.0
  easy_refresh: ^3.4.0
  ff_annotation_route_core: ^2.0.7
  ff_annotation_route_library: ^3.0.0
  flex_color_picker: ^3.7.0
  bbob_dart: ^0.2.1
  flutter_bbcode: ^1.5.0
  flutter_inappwebview: ^6.1.5
  flutter_styled_toast: ^2.2.1
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0
  github: ^9.24.0
  hive_ce: ^2.11.1
  hive_ce_flutter: ^2.3.0
  infinite_carousel: ^1.1.1
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  skeletonizer: ^2.0.1
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.0
  win32_registry: ^2.1.0

  #(Android)SAF存储
  docman: ^1.2.0
  waterfall_flow: ^3.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  #hive_ce_generator: 1.8.1
  hive_ce_generator: 1.8.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  #fonts:
  #  - family: MiSansFont
  #    fonts:
  #      - asset: assets/fonts/MiSans-Regular.ttf
        
  assets:
    - assets/icons/icon.png
    - assets/icons/bangumi_logo.png
    - assets/bangumiSticker/01-23 dsm/
    - assets/bangumiSticker/24-125 Cinnamor/
    - assets/bangumiSticker/200-238 神戶小鳥/
    - assets/bangumiSticker/500-529 五行行行行行啊/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  #web:
  #  generate: true
  #  image_path: "path/to/image.png"
  #  background_color: "#hexcode"
  #  theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  #macos:
  #  generate: true
  #  image_path: "path/to/image.png"
